/* ============================================================
   KOZMO İÇERİK HAVUZU
   Yazım ilkeleri: ikinci tekil şahıs, somut imge, tek fikir,
   klişe yasağı, hafif oyunbaz Kozmo sesi.
   ============================================================ */

export const AURA_COLORS = [
  { ad: "Gece Safiri", hex: "#3d6bd6" },
  { ad: "Altın Şafak", hex: "#d4af37" },
  { ad: "Menekşe Sisi", hex: "#9a76e8" },
  { ad: "Nane Nefesi", hex: "#4fc4a8" },
  { ad: "Gül Kuvarsı", hex: "#e08aab" },
  { ad: "Turkuaz Derinlik", hex: "#35b3b3" },
  { ad: "Amber Közü", hex: "#e2884a" },
  { ad: "Lavanta Gölgesi", hex: "#a795e6" },
  { ad: "Yakut Kıvılcımı", hex: "#d65a80" },
  { ad: "Buz Aydınlığı", hex: "#8fc6ec" },
];

export const MOTTOS = [
  "Yön, hızdan önce gelir.",
  "Gökyüzü acele etmez; yine de her şeye yetişir.",
  "Bugün küçük bir adım, yarın bir yörünge.",
  "Işığını kısma; gölgeler kendi işini görür.",
  "Sabır da bir tür harekettir.",
  "En uzun gece bile sabaha borçludur.",
  "Sorulmayan soru, kapanmayan kapıdır.",
  "Kalbin pusulası manyetik fırtına tanımaz.",
  "Bazen durmak, en cesur manevradır.",
  "Yıldızlar plan yapmaz; parlar.",
  "Belirsizlik, henüz yazılmamış iyi haberdir.",
  "Kendi gökyüzünün tek sakini sensin.",
  "Bugünün tek görevi: dünden bir milim ileri.",
  "Rüzgârı seçemezsin; yelkeni seçersin.",
  "Karanlık, yıldızların sahnesidir.",
  "Acele eden ışık bile yolda kırılır.",
  "Küçük niyetler, büyük yörüngeler açar.",
  "Sükûnet, gürültünün en iyi cevabıdır.",
  "Her dolunay bir hilalden başladı.",
  "Cesaret, korkunun düzenlenmiş halidir.",
  "Bugün ektiğin sabır, yarın gölgesinde oturacağın ağaç.",
  "Yolun uzunluğu, adımın değerini düşürmez.",
  "İyi sorular, hazır cevaplardan uzun yaşar.",
  "Gökyüzü haritası olanın gecesi kaybolmaz.",
  "Kıyamete değil, kahvaltıya odaklan.",
  "Bir kapı kapanınca koridora çık; pencereler oradadır.",
  "Duyduğun her fırtına sana yağmaz.",
  "Nazik olmak, yumuşak olmak değildir.",
  "Zirve, mola verenleri de bekler.",
  "Kendine anlattığın hikâyeyi güzel yaz; içinde yaşayacaksın.",
  "Ay bile evre evre büyür.",
  "Bugün 'hayır' demek, yarına 'evet' demektir.",
  "Şans, hazırlıklı olanın takma adıdır.",
  "Derin nefes, en kısa tatildir.",
  "Işık hızının bile bir sınırı var; senin de olabilir.",
  "En iyi manzara, tırmananın hakkıdır.",
];

export const GUNUN_CUMLESI = {
  ates: [
    "Bugün frenin değil, direksiyonun önemli — hız zaten sende.",
    "Kıvılcım sende; yangını nereye kuracağını seç.",
    "Sabırsızlığın haklı olabilir ama zamanlaman daha haklı.",
    "Parlamak için sahne bekleme; koridor da yeter.",
    "Bugün 'sonra' kelimesini sözlüğünden çıkar; sahne şimdi.",
    "Ateşin güzelliği ölçüsünde; bugün ocağı sen ayarlıyorsun.",
    "Cesaretin bulaşıcı; bugün kime bulaştıracağını seç.",
    "Hızını kimseye açıklama; yönünü kendine açıkla, yeter.",
    "Bugün ilk adımı atan sen ol; ikincisi hep daha kolaydır.",
    "Öfke bugün pahalı; enerjine zam gelmiş say, harcamayı seç.",
    "Ateşin en güzel hali kontrollüsü; bugün közü sen ayarla.",
    "Bir işi bugün bitir; yarım kalan seni gece uyandırır.",
    "Cesaret bugün ucuz değil ama sende fazlası var; birine ödünç ver.",
    "Hız güzel, fren de bir marifet; bugün ikisini birden kullan.",
    "Seni durduran tek şey, henüz atmadığın adım.",
    "Kıvılcımı sakınma; bazı yangınlar ısıtmak içindir.",
    "İçinden 'ben yaparım' geçiyorsa, geçme; yap.",
    "Rakibin yok, ritmin var; kendi tempona koş.",
    "İlk hamleyi bekleyen çok; masaya sen otur.",
    "Sabırsızlık bugün akıl hocası değil; onu koridorda beklet.",
    "Bir kapıyı çal; en kötü ihtimalle sesin duyulur.",
    "Bugün kısılan ateş değil, körüklenen ateşsin.",
    "Yorgunluk cesaretin değil, molanın işareti; kısa dinlen, devam et.",
    "Büyük laf değil, küçük iş konuşsun.",
  ],
  toprak: [
    "Bugün attığın temel, sessizce yıllarca taşıyacak.",
    "Yavaş demek geç demek değil; sen bunu herkesten iyi bilirsin.",
    "Kontrol listesi güzel; ama bir maddeyi de kalbine bırak.",
    "Kök salmak da bir yolculuktur — üstelik gidilenlerin en derini.",
    "Bugün küçük bir düzen kur; kaos kendiliğinden küçülür.",
    "Senin 'yavaş'ın, çoğunun 'sağlam'ı — tempoyu savunma, sürdür.",
    "Bir işi bitirmenin hazzı bugün sana iyi gelecek; en küçüğünden başla.",
    "Toprak sabırlıdır ama nadasa da inanır; bugün biraz nadas.",
    "Elinle dokunduğun bir şey üret; zihnin sana teşekkür edecek.",
    "Bugün biriktirdiğin sadece para değil; güven de faiz getirir.",
    "Acele bugün ustan değil; sabır senin zanaatın.",
    "Bir taşı yerine koy; duvar kendini yarın örer.",
    "Sağlam olan yavaş kurulur; sen zamandan yana bahse gir.",
    "Bugün küçük bir söz ver ve tut; güven böyle büyür.",
    "Elin işte, aklın işte olsun; ikisi ayrı düşerse iş aksar.",
    "Düzen bugün süs değil, dinlenme yeri; bir köşeyi topla.",
    "Yavaş yürü ama durma; kaplumbağanın da bir hedefi vardır.",
    "Bugün temeli düşün; kat çıkmak yarının işi.",
    "Kök salmak zaman ister; bugün acele değil, sabır ek.",
    "Bir işi tam yap; yarım bırakılan seni iki kez yorar.",
    "Bugün sözünü tut, kartını göster; sağlamlık gösteriştendir.",
    "Toprak vaat etmez, verir; sen de öyle ol.",
    "Bugün bir düzen kur, kaos kendiliğinden küçülür.",
    "Sakin akan derin akar; bugün acele suları bulanık.",
  ],
  hava: [
    "Aklındaki on fikirden biri altın; bugün eleme günü.",
    "Konuşarak çözülür — ama önce dinleyerek.",
    "Zihnin rüzgârlı; uçurtma uçurmak için ideal hava.",
    "Bugün bir cümlen, birinin haftasını değiştirebilir.",
    "Fikrin güzel; bugün onu tek bir cümleye sığdırmayı dene.",
    "Bugün köprü ol, taraf değil.",
    "Merakın bugün pusulan; ama tek yöne bak, dört yöne değil.",
    "Sohbetin en değerli anı, senin sustuğun an olabilir.",
    "Bugün notunu al; zihin uçurtmadır, ip kâğıttır.",
    "Yeni bir bakış açısı yeni bir oda gibidir; bugün kapıyı arala.",
    "Zihnin bugün kalabalık; bir fikri seç, gerisini uğurla.",
    "Bir soru sor; cevaptan çok soru açar kapıları.",
    "Dinlemek bugün konuşmaktan çok iş görecek.",
    "Fikrin uçuyor; ipini bir kâğıda bağla, kaçmasın.",
    "Bugün bir cümleni tart; ağzından çıkan geri girmez.",
    "İki fikri çarpıştır; kıvılcım aradaki boşluktan çıkar.",
    "Bir köprü kur; taraf olmak kolay, bağ kurmak marifet.",
    "Kafandaki gürültüyü yaz; kâğıt, zihinden sakin bir dinleyici.",
    "Espri de bir zekâdır; yerinde bir laf buzları eritir.",
    "Az konuş, çok dinle; bugün en iyi cümlen sessizliğin olabilir.",
    "Bir fikrini bugün birine anlat; anlatınca netleşir.",
    "Zihnin bugün rüzgârlı; uçurtma uçurmak için ideal hava.",
    "Dağınık düşünce kıvılcım, odaklı düşünce fener; bugün feneri seç.",
  ],
  su: [
    "Hislerin bugün pusuladan hassas; onlara güvenebilirsin.",
    "Derin sular sessiz akar — sen de öyle, ve bu bir güç.",
    "Bugün birini anlamak, anlaşılmaktan daha çok iyileştirecek.",
    "Dalga geçer; deniz kalır. Sen denizsin.",
    "Bugün sezgin veri, duygun pusula; ikisini de ciddiye al.",
    "Sınır koymak sevgiyi azaltmaz; suyu berraklaştırır.",
    "Bugün birine 'seni duyuyorum' de; dalgaların dili budur.",
    "Gözyaşı da yağmur gibidir; sonrası hep daha berrak.",
    "İçindeki gelgiti düzeltmeye uğraşma; Ay bile karışmıyor.",
    "Bugün kendine bir liman ol; açık deniz yarın da orada.",
    "Sezgin bugün konuşuyor; kelime aramasa da onu duy.",
    "Bir sınır çek; su, kıyısı olduğunda daha berrak akar.",
    "Birine 'seni duyuyorum' de; en derin cümle bu olabilir.",
    "İçindeki gelgiti düzeltme; Ay bile ona karışmıyor.",
    "Bir duygunu adlandır; ad koymak, yükün yarısıdır.",
    "Derinliğin bugün gücün; sığ sular çabuk ısınır, çabuk soğur.",
    "Bir anıya takılma; su, geçmişe değil denize akar.",
    "Kendine, en sevdiğin insana davrandığın gibi davran.",
    "Gözyaşı da yağmurdur; sonrası hep daha berrak.",
    "Susmak da bir cevap; her dalgaya taş atma.",
    "İçini bir kâğıda dök; taşan su, kanal bulunca sakinleşir.",
    "Birinin halini anla; anlamak, çözmekten çok iyileştirir.",
    "Duyguna güven ama esir olma; sen denizsin, dalga değil.",
    "Bugün yavaşla; derin sular acele etmez, yine de varır.",
  ],
};

export const MOON_SENT = {
  uyumlu: [
    "Ay'ın bugünkü konumu senin doğanla aynı dilde konuşuyor; sezgilerinle mantığın nadir bir ateşkeste.",
    "Ay bugün senin frekansında yayın yapıyor; iç sesinle dış dünya aynı kanalda.",
    "Gökyüzü bugün senden yana esiyor; sezgine attığın adımlar zeminde karşılık buluyor.",
    "Ay bugün doğanla el sıkışmış; içinden geçenle dışarıda olan bugün örtüşüyor.",
    "Bugün gökyüzü sana kolaylık tanıyor; akışa güvenmek her zamankinden mantıklı.",
    "Ay senin tarafında bugün; ertelediğin bir şeyi başlatmak için doğal bir gün.",
  ],
  gergin: [
    "Ay bugün doğanla küçük bir söz düellosunda; kararlarını bir gece bekletmek fena fikir değil.",
    "Ay bugün doğana ters köşe; ilk tepkin yerine ikinci düşüncen konuşsun.",
    "Gökyüzünde hafif bir parazit var; önemli konuşmaları netlik dönene kadar kısa tut.",
    "Ay bugün seni biraz zorluyor; acele karar yerine sabırlı gözlem daha çok iş görür.",
    "Bugün gökyüzü hafif çelişkili; hislerinle hemen hareket etme, bir demlensin.",
    "Ay bugün ritmini şaşırtabilir; büyük hamleleri yarına bırakmak bugünün akıllıca seçimi.",
  ],
  notr: [
    "Gökyüzü bugün tarafsız bir hakem; sonucu senin hamlelerin belirleyecek.",
    "Ay bugün kendi işinde; sahne boş, senaryoyu sen yazıyorsun.",
    "Gökyüzü bugün yorum yapmıyor; günün rengini senin seçimlerin belirleyecek.",
    "Ay bugün ne itiyor ne çekiyor; direksiyon tamamen sende.",
    "Gökyüzü bugün sessiz; bu sessizlik bir boşluk değil, sana bırakılmış bir alan.",
    "Ay bugün seyirci koltuğunda; günün kahramanı da senaristi de sensin.",
  ],
};

export const CAT_HIGH = {
  aile: [
    "Aile cephesi bugün en güçlü alanın; ertelenmiş bir konuşma için gökyüzü yeşil ışık yakıyor.",
    "Aile tarafında bugün bir yumuşama var; küçük bir telefon büyük bir düğümü çözebilir.",
    "Ev tarafı bugün destekleyici; ortak bir plan kurmak için doğru gün.",
    "Bugün aileyle aran akışta; uzaktakine bir haber, yakındakine bir jest iyi oturur.",
    "Aile bağların bugün sana güç veriyor; destek istemekten çekinme, tam sırası.",
    "Bugün evde tatlı bir denge var; paylaşılan basit bir an, günü güzelleştirir.",
  ],
  is: [
    "İş tarafında rüzgâr arkandan esiyor; görünür olmaktan çekinme.",
    "İşte bugün görünürlük kazanıyorsun; fikrini masaya koymaktan çekinme.",
    "Mesleki tarafta kapılar aralık; bir talebini dile getirmek için uygun zemin.",
    "Bugün işte sözün geçerli; net bir talebi bugün iletmek yarına kalmasın.",
    "İş cephende bugün akış lehine; başlattığın şey beklediğinden hızlı ilerleyebilir.",
    "Bugün mesleki sezgin keskin; bir fırsatı fark edersen üstüne gitmenin günü.",
  ],
  ask: [
    "Aşk göstergen yüksek; küçük bir jest, büyük bir yankı bulabilir.",
    "Kalp göstergen bugün cömert; ilk mesajı bekleme, gönder.",
    "Aşkta bugün anlaşılma şansın yüksek; ertelediğin cümleyi kur.",
    "Bugün duygularını göstermek kolay; içten bir söz, bugün fazlasıyla karşılık bulur.",
    "Aşk tarafında bugün kapı açık; yakınlaşmak isteyen adımı bugün atsın.",
    "Bugün sıcaklığın fark ediliyor; sevdiğine ayıracağın kısa bir an uzun iz bırakır.",
  ],
  para: [
    "Para akışında fırsat kokusu var; ama fırsat, acele ile karıştırılmamalı.",
    "Para tarafında bugün berrak düşünüyorsun; planlama için ideal.",
    "Finansal sezgin bugün keskin; ama keskinlik, acele demek değil.",
    "Bugün bütçene soğukkanlı bakabiliyorsun; bir düzenleme için sakin ve doğru gün.",
    "Para tarafında bugün kontrol sende; küçük ama sağlam bir adım, ileride rahatlatır.",
    "Bugün maddi konularda net görüyorsun; ertelediğin bir hesabı gözden geçirmek iyi gelir.",
  ],
};

export const CAT_RISKY = {
  aile: [
    "Aile içinde alınganlık katsayısı yüksek; espri dozunu bugün bir tık düşür.",
    "Aile içi eski bir konu bugün alevlenmeye hazır; kibriti sen çakma.",
    "Bugün evde tartışmanın maliyeti yüksek; ertele, yarın ucuzlar.",
    "Bugün ailede kelimeler kolay yanlış anlaşılır; net konuş, varsayımı bırak.",
    "Aile tarafında bugün sabır bütçen sınırlı; büyük konuyu daha sakin bir güne sakla.",
    "Bugün evde küçük bir gerginlik olabilir; ilk sözü sen yumuşat, kâr sende kalır.",
  ],
  is: [
    "İşte imza atmadan önce iki kez oku; bugün küçük harfler günü.",
    "İşte bugün yanlış anlaşılma riski yüksek; iki kez oku, bir kez gönder.",
    "Bugün işte aceleyle verilen söz, yarın faiziyle geri döner.",
    "İş tarafında bugün detay atlanabilir; önemli bir işi göndermeden bir kez daha gözden geçir.",
    "Bugün işte tartışmaya değmez konular çıkabilir; enerjini gerçek önceliğe sakla.",
    "İş cephende bugün acele karar riskli; bir gün beklemek çoğu zaman en ucuz sigorta.",
  ],
  ask: [
    "Aşkta varsayım yapma; sor. Bugün tahminler pahalı.",
    "Aşkta bugün kıskançlık pahalı bir aksesuar; takma.",
    "Partnerinin sessizliği hakkında roman yazma; sor, kısa cevabı al.",
    "Bugün aşkta küçük bir söz büyük anlaşılabilir; niyetini açık tut, ima etme.",
    "Aşk tarafında bugün alınganlık kolay; karşındakine de bir gün kredisi aç.",
    "Bugün duygusal bir tepki hızlı gelebilir; cevabını yazmadan önce bir nefes al.",
  ],
  para: [
    "Para konusunda büyük kararları yarına saklamak bugünkü en kârlı yatırım olabilir.",
    "Bugün 'kaçmaz fırsat' diye gelen her şey kaçar; bırak kaçsın.",
    "Cüzdanın bugün duygusal kararlara açık; büyük harcamayı bir gün beklet.",
    "Bugün maddi bir konuda acele etme; sabah net görünen, akşam daha da netleşir.",
    "Para tarafında bugün 'sonra pişman olurum' dediğin şeyi bugün alma; liste yap, beklet.",
    "Bugün bütçende küçük bir sızıntı gözden kaçabilir; harcamaya bir bak, tıka.",
  ],
};

export const MOODS = [
  {
    k: "huzurlu", ad: "Huzurlu", rx: [
      "Bu dengeyi not et: bugün seni sakinleştiren şeyi yarına da davet et. Akşam on dakikalık ekransız bir mola, bu huzurun faizidir.",
      "Huzur, korunması gereken bir bahçe. Bugün ona bir çit çek: gündeminden bir konuyu azalt.",
      "İyi giden bir şey var; bugün onu fark et ve adını koy. Fark edilen huzur, iki kez yaşanır.",
      "Bu sakinlik bir fırsat: uzun süredir ertelediğin küçük bir işi bugün, telaşsızca hallet. Dingin zihin, en verimli zihindir.",
      "Bugün kimseye bir şey kanıtlaman gerekmiyor. Bu boşluğu bir yürüyüşle ya da sevdiğin bir sesle doldur; huzur tüketilmez, beslenir.",
    ],
  },
  {
    k: "gergin", ad: "Gergin", rx: [
      "Omuzlarını kulaklarından uzaklaştır — evet, şimdi. Dört saniye al, altı saniye ver; üç tur. Gerginlik mesajdır, ceza değil.",
      "Gerginliğin bir adresi var; onu bul ve küçült: 'her şey' değil, 'şu iş'. Ad koymak, yükün yarısıdır.",
      "Bugün zihnin kalabalık; bir kâğıda seni geren üç şeyi yaz. Dışarı çıkan düşünce, içeride büyüdüğü kadar büyümez.",
      "Bir bardak su iç, pencereden uzağa bak. Bu iki dakikalık ara, bugün vereceğin en isabetli karar olabilir.",
      "Her şeyi bugün çözmen gerekmiyor. En küçük düğümü seç, sadece onu gevşet; gerisi yarının işi, sırası gelecek.",
    ],
  },
  {
    k: "umutlu", ad: "Umutlu", rx: [
      "Umut, eylemle beslenir: bugün o umudun yönünde atılabilecek en küçük adımı seç ve at. Küçüklüğü seni yanıltmasın.",
      "Umudunu bir tarihe bağla: 'bir gün' değil, 'perşembe'. Takvim, umudun en iyi arkadaşıdır.",
      "Bugün bu iyi hissi birine bulaştır: kısa bir mesajla, içten bir teşekkürle. Paylaşılan umut, bölünmez, çoğalır.",
      "İçindeki 'olabilir'i 'nasıl olur'a çevir. Bir kâğıda tek bir ilk adım yaz; umut, plana dönüşünce ayakları yere basar.",
      "Bugün cesaretin yüksek; en çok korktuğun o küçük işi tam da bugün başlat. Umutlu günler, ertelenenlerin panzehiridir.",
    ],
  },
  {
    k: "yorgun", ad: "Yorgun", rx: [
      "Bugün kahramanlık günü değil, bakım günü. Bir işi sil, bir işi ertele, kalanı yavaşlat. Gökyüzü de bazen bulutlanır.",
      "Yorgunluk, borcun faturasıdır; bugün asgari ödemeyi yap: erken uyu, telefonu erken bırak.",
      "Bugün listeni yarıya indir; kalan yarısı seni yarın bekler, kaçmaz. Dinlenmek de bir üretkenliktir, tembellik değil.",
      "Kendine küçük bir iyilik borçlusun: on dakika hiçbir şey yapmadan otur. Boş geçen o zaman, aslında en dolu yatırımdır.",
      "Bugün 'hayır' demek de bir güç. Enerjini gerçekten değeni için sakla; her davete yetişmen gerekmiyor.",
    ],
  },
  {
    k: "kararsiz", ad: "Kararsız", rx: [
      "İki seçeneği de yazı-tura at — para havadayken hangisini dilediğine dikkat et. Cevabın çoğu zaman oradadır.",
      "Kararsızlık çoğu zaman bilgi eksiği değil, kriter eksiğidir. Bugün tek kriter seç: hangisi seni büyütür?",
      "Küçük kararı hemen ver, büyüğü bir geceye yatır. Sabah aynı şeyi hâlâ istiyorsan, o senin cevabındır.",
      "Bir kâğıdı ikiye böl, iki tarafı da yaz. Görünür hale gelen seçim, kafanın içinde döndüğünden daha nettir.",
      "Yanlış karar, kararsızlıktan iyidir; birinden ders çıkar, diğerinden çıkamazsın. Bugün küçük bir adımla ilerle, dur değil.",
    ],
  },
  {
    k: "enerjik", ad: "Enerjik", rx: [
      "Bu enerjiyi en inatçı işine yatır; kolay işler bu cömertliği hak etmiyor. Akşama bir 'bitti' demenin keyfini sakla.",
      "Enerji taşarken hedef küçültme; bugün büyük taşı kaldır, çakıllar yarına.",
      "Bugün başlamak için beklediğin o iş var ya — işte o. Momentum bugün senin yanında; harekete geçir, tökezlemeden.",
      "Bu ivmeyi dağıtma; tek bir hedefe kilitle. Dört işi yarım bırakmaktansa bir işi tam bitirmek, bugünün en tatmin edici hamlesi.",
      "Enerjini yalnız işe değil, birine de ayır: uzun süredir aramadığın birine bugün ulaş. Coşku, paylaşınca uzar.",
    ],
  },
  {
    k: "kirilgan", ad: "Kırılgan", rx: [
      "Kırılganlık, ince ayarlı bir radar demektir. Bugün kendine, en sevdiğin insana davrandığın gibi davran. Sınır koymak da şefkattir.",
      "Bugün cildin ince; dünyayı kalınlaştıramazsın ama dozunu ayarlayabilirsin. Haberleri ve akışı azalt.",
      "Bugün kendine yumuşak ol; herkes her gün güçlü olmak zorunda değil. Sıcak bir içecek, sevdiğin bir battaniye — küçük şeyler bugün büyük iş görür.",
      "İçini dökebileceğin birini ara bugün; yük, paylaşılınca hafifler. Yalnız taşımak zorunda değilsin, kimse değil.",
      "Bugün 'yeterince iyiyim' de, gerisini bırak. Kendine gösterdiğin sabır, en çok bugün fark yaratacak.",
    ],
  },
  {
    k: "merakli", ad: "Meraklı", rx: [
      "Merakını tek soruya odakla ve yirmi dakika sadece onun peşinden git. Dağınık merak kıvılcımdır; odaklı merak fener.",
      "Merakının peşine bir defter tak; akşam üç satır not, sabah bir keşfe dönüşür.",
      "Bugün öğrenmek istediğin o şeyi ertelemeden araştır. Beslenen merak büyür, bastırılan söner; sen büyüteni seç.",
      "Bir soru sor bugün — birine, bir kitaba, kendine. En iyi cevaplar, sorma cesaretini gösterenleri bekler.",
      "Merakın bugün pusulan; onu alıştığın bir yola değil, hiç gitmediğin bir sokağa çevir. Küçük bir keşif günü kurtarır.",
    ],
  },
];

/* Dokununca açılan sade terim açıklamaları */
export const GLOSS = {
  aura: "Aura: günün sana özel rengi ve mottosu — Kozmo'nun paylaşılabilir günlük kartı.",
  checkin: "Check-in: o anki hissini seçersin, Kozmo sana küçük bir öneri sunar.",
  faz: {
    "Yeni Ay": "Güneş ile Ay aynı hizada; başlangıçların evresi.",
    "Büyüyen Hilal": "Ay büyümeye başladı; niyetleri besleme zamanı.",
    "İlk Dördün": "Ayın yarısı aydınlık; ilk engeller ve kararlar evresi.",
    "Şişkin Ay": "Dolunaya yaklaşırken enerji birikir; son rötuş zamanı.",
    "Dolunay": "Ay tam karşıda ve dopdolu; sonuçların görünür olduğu evre.",
    "Küçülen Şişkin": "Dolunay sonrası; hasat ve paylaşma evresi.",
    "Son Dördün": "Ay küçülüyor; bırakma ve sadeleşme zamanı.",
    "Balzamik Hilal": "Yeni Ay'dan hemen önceki ince hilal; dinlenme ve kapanış evresi.",
  },
};
